### ISSUE TITLE
[EPIC] Make external calendar events be available for selection when creating super events

### ISSUE THREAD

**Issue by sandeep-ps** [rokwire/events-manager#1044]
### Description
As a user, I want to be able to choose events from external calendar systems like WebTools when creating a super event so that I can create super events from existing external calendar events quickly by avoiding the task of duplicating that information within the User Events space. Since these events are coming from a different system, I shouldn't have any write permissions on those events. I.e., within the User Events space, I should not be able to edit, delete, or change the published status of calendar events that will be part of a super event. The super event can have a combination of user-created events and calendar events (non-editable).

The following are the features of this Epic:

- [ ] [FEATURE] Users can search and add calendar events as sub-event of a super event
- [ ] [FEATURE] Users can navigate to calendar events that have been added as a sub-event of a super event
- [ ] [FEATURE] Users cannot edit or make changes to the calendar events that are part of a super event
- [ ] ?

### Acceptance Criteria
The user can choose events from external calendar systems like WebTools when creating a super event, and they cannot make any changes to the calendar events.
